#!/bin/sh
#
# PROVIDE: wireproxy-awg
# REQUIRE: DAEMON
# KEYWORD: nojail
#

#
# Add the following lines to /etc/rc.conf to enable wireproxy-awg:
#
#wireproxy_enable="YES"
#

. /etc/rc.subr

name=wireproxy-awg
rcvar=wireproxy_enable

load_rc_config $name
procname="/bin/wireproxy-awg"

wireproxy_enable=${wireproxy_enable:-"NO"}

wireproxy_bin=/bin/wireproxy-awg
wireproxy_conf=/etc/wireproxy-awg.conf

command=${wireproxy_bin}
command_args="-s -d -c ${wireproxy_conf}"

run_rc_command "$1"
